version: '3'

services:
  app:
    container_name: test-app
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    environment:
      BASE_URL: "http://localhost:5000"
      MONGODB_URI: "mongodb://mongo:27017/url_shortener"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
